package com.plnus.puerility.counter.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.plnus.puerility.counter.model.entity.RouteEntity;

import com.plnus.puerility.counter.db.RouteEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig routeEntityDaoConfig;

    private final RouteEntityDao routeEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        routeEntityDaoConfig = daoConfigMap.get(RouteEntityDao.class).clone();
        routeEntityDaoConfig.initIdentityScope(type);

        routeEntityDao = new RouteEntityDao(routeEntityDaoConfig, this);

        registerDao(RouteEntity.class, routeEntityDao);
    }
    
    public void clear() {
        routeEntityDaoConfig.clearIdentityScope();
    }

    public RouteEntityDao getRouteEntityDao() {
        return routeEntityDao;
    }

}
